version: '3.7'

services:

  contacts.api:
    image: nibro7778/contacts.api
    build:
      context: .
      dockerfile: src/Services/Contacts Service/Contacts.API/Dockerfile
    ports:
      - '5001:80'

  events.api:
    image: nibro7778/events.api
    build:
      context: .
      dockerfile: src/Services/Events Service/Events.API/Dockerfile
    ports:
      - '5002:80'

  notes.api:
    image: nibro7778/notes.api
    build:
      context: .
      dockerfile: src/Services/Notes Service/Notes.API/Dockerfile
    ports:
      - '5003:80'